---
# defaults file for vpc
ami: "ami-xxxxxxx"
aws_account_num: "{{ vault_aws_account_num }}"
public_key: '{{ envname }}'
region: eu-west-1
vpc_infra: "vpc-*******"
cidr_block_infra: "172.30.0.0/16"
b_class_cidr: "{{ cidr_block.split('.')[0] }}.{{ cidr_block.split('.')[1] }}"
subnets:
  public:
    subnet_name: "public-{{ envname }}"
    ipv4_cidr: "{{ b_class_cidr }}.1.0/24"
    availability_zone: "{{ region }}a"
  private:
    subnet_name: "private-{{ envname }}"
    ipv4_cidr: "{{ b_class_cidr }}.2.0/24"
    availability_zone: "{{ region }}a"
instances:
  - role: webserver
    subnet: public
    type: t2.micro
    volumes:
      - device_name: /dev/sda1
        volume_size: 8
    groups: [allow_vpc, allow_ssh]
    public_access: True
  - role: backend
    priority: "1"
    subnet: private
    type: t2.micro
    volumes:
      - device_name: /dev/sda1
        volume_size: 8
    groups: [allow_vpc, allow_ssh]
# ansible varialbes for infra security groups
sg_infra_elasticsearch_kibana: sg-xxxxxxxx
sg_infra_default_vpn_ssh: sg-xxxxxxxx
sg_infra_vpn: sg-xxxxxxxx
sg_infra_logstash: sg-xxxxxxxx
sg_infra_artifactory: sg-xxxxxxxx
sg_infra_jenkins: sg-xxxxxxxx 

security_groups:
    - description: Allow SSH from VPN
      name: "{{ envname }}_allow_ssh_from_vpn"
      rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{ sg_infra_vpn }}"
    - description: Allow 80 from VPN
      name: "{{ envname }}_allow_80_from_vpn"
      rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ sg_infra_vpn }}"
    - description: Web load balancer
      name: "{{ envname }}_allow_web_lb"
      rules:
          - proto: tcp
            cidr_ip: 0.0.0.0/0
            from_port: 80
            to_port: 80
          - proto: tcp
            cidr_ip: 0.0.0.0/0
            from_port: 80
            to_port: 80
    - description: From Application load balancer
      name: "{{ envname }}_allow_alb"
      rules:
          - proto: tcp
            cidr_ip: 10.0.0.0/8
            from_port: 80
            to_port: 80
# variables for service setup
aws_access_key: "{{ vault_aws_access_key }}"
aws_secret_access_key: "{{ vault_aws_secret_access_key }}"